### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by BertschInnovation** [piwik/piwik-dotnet-tracker#19]
Does not work in UWP.

**Comment by mattab** [comment]
Hi @BertschInnovation 
Could you please provide more information on what is the problem, and what it would take to solve it?

Thank you

**Comment by mattab** [comment]
Please share more info when you can

**Comment by DerGary** [comment]
Hi @mattab,

I also just tried to add the Piwik.Tracker NuGet Package to an UWP App but the install failed with the error: 
`Package restore failed. Rolling back package changes for 'App1'.`
So thats not really a meaningfull error message so I went and looked at the output:
```
Restoring packages for 'App1'.
Restoring packages for c:\Projects\App1\App1\project.json...
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
Piwik.Tracker 2.16.0 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'App1'.
Package restore failed. Rolling back package changes for 'App1'.
========== Finished ==========
```
After that I took a look at the current Piwik NuGet Package which publishes the dll in the .net40 folder. I don't really know much about the different Framework types but what i know is that to be compatible with UWP it should be in the .netcore50 or uap10.0 folder but just putting it in this folder is of course not going to work so it must also be build for .netcore50, so I went and tried to create a new ClassLibrary project that targets .Net for Windows Universal and copied all the code to it. I could resolve some of the dependencies but the Namespace System.Security.Cryptography which should be in the mscorlib is just not present for .Net for Windows Universal.

Maybe there is a way around this? I don't really know much about the different Frameworks and I am at my wit's end now.

Maybe you have some ideas to fix this we would like to add Piwik to our apps since we already have Piwik running.

Thank you
Gary

**Comment by mattab** [comment]
Hi @DerGary please createa a new issue as this one is closed
