### ISSUE TITLE
[API Change] Timeout while tracking multiple events at the same time

### ISSUE THREAD

**Issue by brownsugar** [piwik/piwik-dotnet-tracker#27]
There is a problem while I tried to track some events.

```
private void TrackSomething() {
    Piwik piwik = new Piwik(1, "XXXX");
    piwik.doTrackEvent("XX", "XX", "XX"); // OK
    piwik.doTrackEvent("XX", "XX", "XX"); // OK
    piwik.doTrackEvent("XX", "XX", "XX"); // Timeout
}
```

And I found there's weird bug at `sendRequest()` funtion,
it stucked at the [last line](https://github.com/piwik/piwik-dotnet-tracker/blob/master/Piwik.Tracker/PiwikTracker.cs#L1504) of the function,
after I changed it to:
```
using (HttpWebResponse response = (HttpWebResponse)request.GetResponse()) {
    return response;
}
```
It works fine now.

**Comment by opcon** [comment]
What platform are you running your application on?

I encountered this issue with my application on Mono, but not on Windows.

I think this is partially an issue on Mono's side, where it can't handle many undisposed HttpWebResponses. I fixed it by disposing the HttpWebResponses, but in my code rather than Piwik's

**Comment by brownsugar** [comment]
Hi, I'm on Windows, and I tested on several Windows platforms too.

**Comment by julienmoumne** [comment]
fixed in https://github.com/piwik/piwik-dotnet-tracker/pull/30
