### ISSUE TITLE
Develop automated tests

### ISSUE THREAD

**Issue by julienmoumne** [piwik/piwik-dotnet-tracker#7]
As discussed in #29, a http mocking library will be used to verify the requests are received and have the expected format (ie. the right piwik parameters).

For a more detailed explanation of the approach and its goals see https://github.com/piwik/piwik-dotnet-tracker/pull/46#issuecomment-287613257

**Comment by tetsuo13** [comment]
What's going to be tested? The few mocking libraries mentioned in #29 look like shims on top of `HttpClient` that don't provide much for increasing the dependencies of this project. Also, the idea of spinning up a Docker instance or an otherwise embedded HTTP server seems like overkill here.

If the tests are going to ensure "calling these methods in our library should produce a URL with arguments that match a known-good set" then it you could fake the response handler in `sendRequest()` of a call to `HttpClient` (this ensures no HTTP request is ever made) and test against the `url` parameter in that method which contains the arguments to check.

I can create a quick PoC if interested.

**Comment by julienmoumne** [comment]
Hi Andrei, thank you for your input. If I'm not mistaken Peter has already started working on this. 

We'll definitely like to have your input on the PR.

**Comment by mattab** [comment]
> and test against the url parameter in that method which contains the arguments to check.

(fyi: this is the technique we use to test the `piwik.js` javascript tracker (integration tests will call a fake`piwik.php` endpoint which logs the requests, then we [check](https://github.com/piwik/piwik/blob/3.x-dev/tests/javascript/index.php#L3693-L3696) the expected URL params are found in the requests). and on top we have unit tests to check the methods separately)

**Comment by julienmoumne** [comment]
That's what Peter (@ptr1120) is aiming for + being able to reproduce mismanagement of resources such as the ones that caused timeouts for several users.

**Comment by julienmoumne** [comment]
@ptr1120 implemented several tests in https://github.com/piwik/piwik-dotnet-tracker/pull/42 and https://github.com/piwik/piwik-dotnet-tracker/pull/46

Tests are continuously executed on travis since https://github.com/piwik/piwik-dotnet-tracker/issues/41

Let's close the ticket and continually add more tests in future commits

Let's handle code coverage tracking in https://github.com/piwik/piwik-dotnet-tracker/issues/47
